$schema: https://azuremlschemas.azureedge.net/latest/commandJob.schema.json
code: model
command: >-
  python train.py
  --training_data ${{inputs.training_data}}
  --reg_rate 0.1
inputs:
  training_data: 
    type: uri_folder 
    path: ../production/data
  reg_rate: 0.01
environment: azureml:AzureML-sklearn-0.24-ubuntu18.04-py37-cpu@latest
compute: aml-cluster
experiment_name: diabetes-data-prod
description: Train a classification model on diabetes data using a prod-env dataset as input.