name: Manually trigger an Azure Machine Learning job

on:
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Run Azure ML job
      # run: az ml job create --file ./src/job.yml -g MLops_test -w MLops_test
      run: az ml job create --file src/job.yml
