name: Trigger on push an Azure Machine Learning job

on:
  push:
    branches:
      - main

jobs:
  dev_train:
    runs-on: ubuntu-latest
    environment: test_env
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Run dev Azure ML job
      # run: az ml job create --file ./src/job.yml -g MLops_test -w MLops_test
      run: az ml job create --file src/dev-job.yml -g MLops_test -w MLops_test -s
  prod_train:
    needs: dev_train
    runs-on: ubuntu-latest
    environment: prod_env
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Run prod Azure ML job
      # run: az ml job create --file ./src/job.yml -g MLops_test -w MLops_test
      run: az ml job create --file src/prod-job.yml -g MLops_test -w MLops_test

